version: '3.9'
services:
  bps-service:
    image: webconbps/bootstrapper:2026.1.4.131-windowsservercore-ltsc2022
    container_name: bps-service
    hostname: bps-service
    environment:
      - STARTUP_MODE=service
      - Configuration__BpsDbConfigRaw=Server=tcp:10.5.0.1,8433;Database=BPS_Config;User ID=sa;Password=P@ssw0rd;TrustServerCertificate=True
      - Configuration__ExternalWebService__Host=bps-service
      - Configuration__ExternalWebService__LicenseServicePort=8002
      - Configuration__ExternalWebService__Port=8003
      - Configuration__BpsSelfHost=true
      - Configuration__Init__DoInit=true
      - Configuration__Init__WebService__LicenseServicePort=8002
      - Configuration__Init__WebService__Port=8003
      - Configuration__Init__ServiceRoles__LicenseService=true
      - Configuration__Init__ServiceRoles__BasicFeatures=true
      - Configuration__Init__ServiceRoles__SolrIndexing=true
    ports:
      - "8002:8002"
      - "8003:8003"
    restart: unless-stopped
    networks:
      - bps

  bps-portal:
    image: webconbps/bootstrapper:2026.1.4.131-windowsservercore-ltsc2022
    container_name: bps-portal
    hostname: bps-portal
    environment:
      - STARTUP_MODE=portal
      - App__ConfigConnection__Value=Server=tcp:${hostname},8433;Database=BPS_Config;User ID=sa;Password=P@ssw0rd;TrustServerCertificate=True
      - App__LogsConnection__Value=Server=tcp:${hostname},8433;Database=BPS_Config;User ID=sa;Password=P@ssw0rd;TrustServerCertificate=True
      - App__IISIntegration=false
      - App__ForceHttpsOnProxy=true
      - App__Kestler__Port=8080
      - App__Kestler__UseSSL=false
      - App__Kestler__Protocol=http
      - App__LogLevel__Value=Warn
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - bps-service
    networks:
      - bps

networks:
  bps:
    driver: nat
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
